### PR TITLE
Fix for HA 2024.12+

### LINKED ISSUE #32: Stopped working after HA update
Core 2024.12.0
Supervisor 2024.11.4

I received the errors below after updating HA.

Logger: homeassistant.loader
Source: loader.py:1074
First occurred: 9:50:55 PM (4 occurrences)
Last logged: 9:50:59 PM

Unexpected exception importing component custom_components.torque_logger
Unexpected exception importing component custom_components.torque_logger2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/torque_logger/__init__.py", line 16, in <module>
    from .api import TorqueReceiveDataView
  File "/config/custom_components/torque_logger/api.py", line 4, in <module>
    import pint
  File "/usr/local/lib/python3.13/site-packages/pint/__init__.py", line 28, in <module>
    from .measurement import Measurement
  File "/usr/local/lib/python3.13/site-packages/pint/measurement.py", line 12, in <module>
    from .quantity import Quantity
  File "/usr/local/lib/python3.13/site-packages/pint/quantity.py", line 69, in <module>
    from .numpy_func import (
    ...<8 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/pint/numpy_func.py", line 875, in <module>
    implement_single_dimensionless_argument_func(func_str)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pint/numpy_func.py", line 864, in implement_single_dimensionless_argument_func
    func = getattr(np, func_str)
  File "/usr/local/lib/python3.13/site-packages/numpy/__init__.py", line 414, in __getattr__
    raise AttributeError("module {!r} has no attribute "
                         "{!r}".format(__name__, attr))
AttributeError: module 'numpy' has no attribute 'cumproduct'. Did you mean: 'cumprod'?


















Logger: homeassistant.setup
Source: setup.py:334
First occurred: 9:50:55 PM (2 occurrences)
Last logged: 9:50:59 PM

Setup failed for custom integration 'torque_logger': Unable to import component: Exception importing custom_components.torque_logger
Setup failed for custom integration 'torque_logger2': Unable to import component: Exception importing custom_components.torque_logger2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/torque_logger/__init__.py", line 16, in <module>
    from .api import TorqueReceiveDataView
  File "/config/custom_components/torque_logger/api.py", line 4, in <module>
    import pint
  File "/usr/local/lib/python3.13/site-packages/pint/__init__.py", line 28, in <module>
    from .measurement import Measurement
  File "/usr/local/lib/python3.13/site-packages/pint/measurement.py", line 12, in <module>
    from .quantity import Quantity
  File "/usr/local/lib/python3.13/site-packages/pint/quantity.py", line 69, in <module>
    from .numpy_func import (
    ...<8 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/pint/numpy_func.py", line 875, in <module>
    implement_single_dimensionless_argument_func(func_str)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pint/numpy_func.py", line 864, in implement_single_dimensionless_argument_func
    func = getattr(np, func_str)
  File "/usr/local/lib/python3.13/site-packages/numpy/__init__.py", line 414, in __getattr__
    raise AttributeError("module {!r} has no attribute "
                         "{!r}".format(__name__, attr))
AttributeError: module 'numpy' has no attribute 'cumproduct'. Did you mean: 'cumprod'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.torque_logger

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/torque_logger/__init__.py", line 16, in <module>
    from .api import TorqueReceiveDataView
  File "/config/custom_components/torque_logger/api.py", line 4, in <module>
    import pint
  File "/usr/local/lib/python3.13/site-packages/pint/__init__.py", line 28, in <module>
    from .measurement import Measurement
  File "/usr/local/lib/python3.13/site-packages/pint/measurement.py", line 12, in <module>
    from .quantity import Quantity
  File "/usr/local/lib/python3.13/site-packages/pint/quantity.py", line 69, in <module>
    from .numpy_func import (
    ...<8 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/pint/numpy_func.py", line 875, in <module>
    implement_single_dimensionless_argument_func(func_str)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pint/numpy_func.py", line 864, in implement_single_dimensionless_argument_func
    func = getattr(np, func_str)
  File "/usr/local/lib/python3.13/site-packages/numpy/__init__.py", line 414, in __getattr__
    raise AttributeError("module {!r} has no attribute "
                         "{!r}".format(__name__, attr))
AttributeError: module 'numpy' has no attribute 'cumproduct'. Did you mean: 'cumprod'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.torque_logger

### PR DESCRIPTION
**Pull request by DominikWrobel**
This is a quick fix for HA 2024.12+.

Fixes #32

### CODE REVIEW

**Comment by junalmeida** [comment]
@DominikWrobel This pull request goes beyond fixes for HomeAssistant. I can accept fixes and improvements to code.

**Review by junalmeida — CHANGES_REQUESTED** [review]
Please remove changes not related to code fixes like images, doc content and license

**Comment by DominikWrobel** [comment]
I've actually testing some new features for this integration, like multiple instances and more data sensors from Torque app. For just the update for this to work with HA 2025.1+ use this version:
[https://github.com/DominikWrobel/homeassistant-torque/releases/tag/v1.2](url)
